---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Carmen Krause"
title: "Was ist Informationswissenschaft und wenn ja, wie viele?"
subtitle: " Ein Veranstaltungsbericht"
urn: "urn:nbn:de:kobv:11-110-18452/22140-9"
date: 2019-12-09
comments: false
sharing: true
footer: true

---