---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Carmen Krause"
title: "Was ist Informationswissenschaft und wenn ja, wie viele?"
subtitle: " Ein Veranstaltungsbericht"
pdf: "master.pdf"
date: 2019-12-09
comments: false
sharing: true
footer: true

---