---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Gabriele Fahrenkrog"
- "Alexandra Jobmann"
- "Redaktion LIBREAS"
title: "Radikale Openness – wie Bibliotheken mit Open Educational Resources und Open Access die UN-Agenda 2030 unterstützen können"
date: 2019-12-08
comments: false
sharing: true
footer: true

---