---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Vanessa Hannesschläger"
- "Redaktion LIBREAS"
title: "Infrastrukturen, Kulturwandel und Nachhaltigkeit – eine Open Policy für das Austrian Centre for Digital Humanities der Österreichischen Akademie der Wissenschaften"
pdf: "master.pdf"
date: 2019-12-08
comments: false
sharing: true
footer: true

---