---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Dorothea Strecker"
title: "Nutzung der Schattenbibliothek Sci-Hub in Deutschland"
pdf: "master.pdf"
date: 2019-12-22
comments: false
sharing: true
footer: true

---