---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Dorothea Strecker"
title: "Nutzung der Schattenbibliothek Sci-Hub in Deutschland"
urn: "urn:nbn:de:kobv:11-110-18452/22143-7"
date: 2019-12-22
comments: false
sharing: true
footer: true

---