---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Ronny Gey"
- "Katrin Leinweber"
- "Alexander Struck"
- "Robert Strötgen"
- "Christian Pietsch"
title: "Workshop @ deRSE19: Libraries for Research Software & Engineers"
urn: "urn:nbn:de:kobv:11-110-18452/22141-5	"
date: 2019-12-09
comments: false
sharing: true
footer: true

---