---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #5 (Sommer/Herbst 2019)"
urn: "urn:nbn:de:kobv:11-110-18452/22139-8"
date: 2019-12-21
comments: false
sharing: true
footer: true

---