---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "36"
year: "2019"
contributor:
- "Robert Strötgen"
- "Daniel Beucke"
- "Redaktion LIBREAS"
title: "Fünf Fragen zur Nachhaltigkeit von Forschungsinfrastrukturen"
pdf: "master.pdf"
date: 2019-12-15
comments: false
sharing: true
footer: true

---